#Simulation Type Toggles
want_avgeps_on: True
want_visualize_on: False

#Output settings
time_sample_rate: 15
fcen: 2.6923
df: 4.6154
nfreq: 200

#Simulation Cell Settings
dpml: 0.1
sx: 0.32
sy: 0.32
sz: 1.0
res: 300

#Nanoantenna Geometry Settings
antenna_thickness: 0.02
altitude: 0.24
r_curvature: 0.01
base: 0.18
antenna_material_name: 'Au'
antenna_fill_material_name: 'air'
antenna_fill_material_thickness: 0.02

#Substrate Settings
substrate_material_name: 'SiO2'
